version: "3.8"

services:
  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  nginx-proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - spring-server